#pragma once

namespace se::cs::dialog::edit_race_window {

	constexpr UINT DIALOG_ID = 159;

	// Default IDs.
	constexpr UINT CONTROL_ID_ID_COMBO = 1083;
	constexpr UINT CONTROL_ID_NEW_BUTTON = 1124;
	constexpr UINT CONTROL_ID_DELETE = 1155;
	constexpr UINT CONTROL_ID_NAME_EDIT = 1000;
	constexpr UINT CONTROL_ID_SKILL_BONUS_1_COMBO = 1125;
	constexpr UINT CONTROL_ID_SKILL_BONUS_1_EDIT = 1032;
	constexpr UINT CONTROL_ID_SKILL_BONUS_2_COMBO = 1126;
	constexpr UINT CONTROL_ID_SKILL_BONUS_2_EDIT = 1033;
	constexpr UINT CONTROL_ID_SKILL_BONUS_3_COMBO = 1127;
	constexpr UINT CONTROL_ID_SKILL_BONUS_3_EDIT = 1034;
	constexpr UINT CONTROL_ID_SKILL_BONUS_4_COMBO = 1128;
	constexpr UINT CONTROL_ID_SKILL_BONUS_4_EDIT = 1035;
	constexpr UINT CONTROL_ID_SKILL_BONUS_5_COMBO = 1129;
	constexpr UINT CONTROL_ID_SKILL_BONUS_5_EDIT = 1036;
	constexpr UINT CONTROL_ID_SKILL_BONUS_6_COMBO = 1130;
	constexpr UINT CONTROL_ID_SKILL_BONUS_6_EDIT = 1037;
	constexpr UINT CONTROL_ID_SKILL_BONUS_7_COMBO = 1131;
	constexpr UINT CONTROL_ID_SKILL_BONUS_7_EDIT = 1038;
	constexpr UINT CONTROL_ID_SKILL_BONUS_ZERO_STATIC = 1132;
	constexpr UINT CONTROL_ID_STR_MALE_EDIT = 1608;
	constexpr UINT CONTROL_ID_STR_FEMALE_EDIT = 1616;
	constexpr UINT CONTROL_ID_INT_MALE_EDIT = 1609;
	constexpr UINT CONTROL_ID_INT_FEMALE_EDIT = 1617;
	constexpr UINT CONTROL_ID_WIL_MALE_EDIT = 1610;
	constexpr UINT CONTROL_ID_WIL_FEMALE_EDIT = 1618;
	constexpr UINT CONTROL_ID_AGI_MALE_EDIT = 1611;
	constexpr UINT CONTROL_ID_AGI_FEMALE_EDIT = 1619;
	constexpr UINT CONTROL_ID_SPD_MALE_EDIT = 1612;
	constexpr UINT CONTROL_ID_SPD_FEMALE_EDIT = 1620;
	constexpr UINT CONTROL_ID_END_MALE_EDIT = 1613;
	constexpr UINT CONTROL_ID_END_FEMALE_EDIT = 1621;
	constexpr UINT CONTROL_ID_PER_MALE_EDIT = 1614;
	constexpr UINT CONTROL_ID_PER_FEMALE_EDIT = 1622;
	constexpr UINT CONTROL_ID_LUC_MALE_EDIT = 1615;
	constexpr UINT CONTROL_ID_LUC_FEMALE_EDIT = 1623;
	constexpr UINT CONTROL_ID_BASE_ATTRIBUTES_MALE_ZERO_STATIC = 1136;
	constexpr UINT CONTROL_ID_BASE_ATTRIBUTES_FEMALE_ZERO_STATIC = 1135;
	constexpr UINT CONTROL_ID_MALE_HEIGHT_EDIT = 1133;
	constexpr UINT CONTROL_ID_MALE_WEIGHT_EDIT = 1491;
	constexpr UINT CONTROL_ID_FEMALE_HEIGHT_EDIT = 1134;
	constexpr UINT CONTROL_ID_FEMALE_WEIGHT_EDIT = 1479;
	constexpr UINT CONTROL_ID_PLAYABLE_CHECKBOX = 1010;
	constexpr UINT CONTROL_ID_BEAST_RACE_CHECKBOX = 1011;
	constexpr UINT CONTROL_ID_SPECIALS_EDIT = 1485;
	constexpr UINT CONTROL_ID_DESCRIPTION_EDIT = 1138;
	constexpr UINT CONTROL_ID_OK_BUTTON = 1;

	// Custom IDs.
	constexpr UINT CONTROL_ID_ID_STATIC = 2001;
	constexpr UINT CONTROL_ID_NAME = 2002;
	constexpr UINT CONTROL_ID_SKILL_BONUS_BUTTON = 2003;
	constexpr UINT CONTROL_ID_BASE_ATTRIBUTES_BUTTON = 2004;
	constexpr UINT CONTROL_ID_MALE_STATIC = 2005;
	constexpr UINT CONTROL_ID_FEMALE_STATIC = 2006;
	constexpr UINT CONTROL_ID_STR_STATIC = 2007;
	constexpr UINT CONTROL_ID_INT_STATIC = 2008;
	constexpr UINT CONTROL_ID_WIL_STATIC = 2009;
	constexpr UINT CONTROL_ID_AGI_STATIC = 2010;
	constexpr UINT CONTROL_ID_SPD_STATIC = 2011;
	constexpr UINT CONTROL_ID_END_STATIC = 2012;
	constexpr UINT CONTROL_ID_PER_STATIC = 2013;
	constexpr UINT CONTROL_ID_LUC_STATIC = 2014;
	constexpr UINT CONTROL_ID_MALE_HEIGHT_STATIC = 2015;
	constexpr UINT CONTROL_ID_MALE_WEIGHT_STATIC = 2016;
	constexpr UINT CONTROL_ID_FEMALE_HEIGHT_STATIC = 2017;
	constexpr UINT CONTROL_ID_FEMALE_WEIGHT_STATIC = 2018;
	constexpr UINT CONTROL_ID_SPECIALS_BUTTON = 2019;
	constexpr UINT CONTROL_ID_DESCRIPTION_BUTTON = 2020;

	void installPatches();
}
#pragma once
