#pragma once

namespace se::cs::dialog::edit_faction_window {

	constexpr UINT DIALOG_ID = 157;

	// Default IDs.
	constexpr UINT CONTROL_ID_ID_COMBO = 1168;
	constexpr UINT CONTROL_ID_NEW_BUTTON = 1124;
	constexpr UINT CONTROL_ID_DELETE_BUTTON = 1155;
	constexpr UINT CONTROL_ID_NAME_EDIT = 1000;
	constexpr UINT CONTROL_ID_REQUIREMENTS_FAVORED_SKILLS_LIST = 1082;
	constexpr UINT CONTROL_ID_REQUIREMENTS_FAVORED_ATTR_1_COMBO = 1159;
	constexpr UINT CONTROL_ID_REQUIREMENTS_FAVORED_ATTR_2_COMBO = 1160;
	constexpr UINT CONTROL_ID_REQUIREMENTS_FAVORED_ATTR_1_EDIT = 1195;
	constexpr UINT CONTROL_ID_REQUIREMENTS_FAVORED_ATTR_2_EDIT = 1194;
	constexpr UINT CONTROL_ID_REQUIREMENTS_FAVORED_SKILL_1_EDIT = 1191;
	constexpr UINT CONTROL_ID_REQUIREMENTS_FAVORED_SKILL_2_EDIT = 1192;
	constexpr UINT CONTROL_ID_REQUIREMENTS_NPC_DISPOSITION_EDIT = 1193;
	constexpr UINT CONTROL_ID_REQUIREMENTS_RANKS_STAT_LIST = 1169;
	constexpr UINT CONTROL_ID_FACTION_REACTIONS_LIST = 1591;
	constexpr UINT CONTROL_ID_FACTION_REACTIONS_FACTION_SEL_COMBO = 1170;
	constexpr UINT CONTROL_ID_FACTION_REACTIONS_REACTION_EDIT = 1001;
	constexpr UINT CONTROL_ID_OK_BUTTON = 1;
	constexpr UINT CONTROL_ID_HIDDEN_FROM_PC_BUTTON = 1006;

	// Custom IDs.
	constexpr UINT CONTROL_ID_ID_STATIC = 2000;
	constexpr UINT CONTROL_ID_NAME_STATIC = 2001;
	constexpr UINT CONTROL_ID_REQUIREMENTS_BUTTON = 2002;
	constexpr UINT CONTROL_ID_REQUIREMENTS_FAVORED_SKILLS_STATIC = 2003;
	constexpr UINT CONTROL_ID_FACTION_REACTIONS_STATIC = 2004;

	void installPatches();
}
#pragma once
#pragma once
