#pragma once

namespace se::cs::dialog::edit_class_window {

	constexpr UINT DIALOG_ID = 160;

	// Default IDs.
	constexpr UINT CONTROL_ID_COMBO = 1158;
	constexpr UINT CONTROL_ID_NEW_BUTTON = 1124;
	constexpr UINT CONTROL_ID_DELETE_BUTTON = 1155;
	constexpr UINT CONTROL_ID_NAME_EDIT = 1029;
	constexpr UINT CONTROL_ID_PRIMARY_ATTRIBUTES_1_COMBO = 1159;
	constexpr UINT CONTROL_ID_PRIMARY_ATTRIBUTES_2_COMBO = 1160;
	constexpr UINT CONTROL_ID_SPECIALIZATION_COMBO = 1157;
	constexpr UINT CONTROL_ID_PLAYABLE_BUTTON = 1010;
	constexpr UINT CONTROL_ID_MAJOR_SKILLS_1_COMBO = 1035;
	constexpr UINT CONTROL_ID_MAJOR_SKILLS_2_COMBO = 1036;
	constexpr UINT CONTROL_ID_MAJOR_SKILLS_3_COMBO = 1037;
	constexpr UINT CONTROL_ID_MAJOR_SKILLS_4_COMBO = 1038;
	constexpr UINT CONTROL_ID_MAJOR_SKILLS_5_COMBO = 1039;
	constexpr UINT CONTROL_ID_MINOR_SKILLS_1_COMBO = 1045;
	constexpr UINT CONTROL_ID_MINOR_SKILLS_2_COMBO = 1046;
	constexpr UINT CONTROL_ID_MINOR_SKILLS_3_COMBO = 1047;
	constexpr UINT CONTROL_ID_MINOR_SKILLS_4_COMBO = 1048;
	constexpr UINT CONTROL_ID_MINOR_SKILLS_5_COMBO = 1049;
	constexpr UINT CONTROL_ID_DESCRIPTION_EDIT = 1138;
	constexpr UINT CONTROL_ID_AUTO_CALC_BUYS_SELLS_BUTTON = 1526;
	constexpr UINT CONTROL_ID_WEAPONS_BUTTON = 1527;
	constexpr UINT CONTROL_ID_ARMOR_BUTTON = 1528;
	constexpr UINT CONTROL_ID_BOOKS_BUTTON = 1530;
	constexpr UINT CONTROL_ID_CLOTHING_BUTTON = 1529;
	constexpr UINT CONTROL_ID_INGREDIENTS_BUTTON = 1531;
	constexpr UINT CONTROL_ID_PICKS_BUTTON = 1532;
	constexpr UINT CONTROL_ID_PROBES_BUTTON = 1533;
	constexpr UINT CONTROL_ID_LIGHTS_BUTTON = 1534;
	constexpr UINT CONTROL_ID_APPARATUS_BUTTON = 1535;
	constexpr UINT CONTROL_ID_REPAIR_ITEMS_BUTTON = 1536;
	constexpr UINT CONTROL_ID_MISCELLANEOUS_BUTTON = 1537;
	constexpr UINT CONTROL_ID_SPELLS_BUTTON = 1538;
	constexpr UINT CONTROL_ID_MAGIC_ITEMS_BUTTON = 1539;
	constexpr UINT CONTROL_ID_POTIONS_BUTTON = 1540;
	constexpr UINT CONTROL_ID_AUTO_CALC_OTHER_BUTTON = 1541;
	constexpr UINT CONTROL_ID_TRAINING_BUTTON = 1542;
	constexpr UINT CONTROL_ID_SPELLMAKING_BUTTON = 1543;
	constexpr UINT CONTROL_ID_ENCHANTING_BUTTON = 1544;
	constexpr UINT CONTROL_ID_REPAIR_BUTTON = 1545;
	constexpr UINT CONTROL_ID_OK_BUTTON = 1;

	// Custom IDs.
	constexpr UINT CONTROL_ID_ID_STATIC = 2000;
	constexpr UINT CONTROL_ID_NAME_STATIC = 2001;
	constexpr UINT CONTROL_ID_PRIMARY_ATTRIBUTES_STATIC = 2002;
	constexpr UINT CONTROL_ID_SPECIALIZATION_STATIC = 2003;
	constexpr UINT CONTROL_ID_MAJOR_SKILLS_STATIC = 2004;
	constexpr UINT CONTROL_ID_MINOR_SKILLS_STATIC = 2005;
	constexpr UINT CONTROL_ID_DESCRIPTION_STATIC = 2006;

	void installPatches();
}
