--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A struct used to store render target data for the map and inventory doll.
--- @class tes3worldControllerRenderTarget : tes3worldControllerRenderCamera
--- @field alphaProperty niAlphaProperty|nil The render target's alpha property.
--- @field directionalLight niDirectionalLight|nil The render target's directional light.
--- @field readbackTexture niSourceTexture|nil The render target's base readback texture.
--- @field renderedTexture niRenderedTexture|nil The render target's rendered texture.
--- @field rendererHeight number The height of the render.
--- @field rendererWidth number The width of the render.
--- @field targetHeight number The height of the render target.
--- @field targetWidth number The width of the render target.
--- @field vertexColorProperty niVertexColorProperty|nil The render target's vertex color property.
--- @field zBufferProperty niZBufferProperty|nil The render target's Z-buffer property.
