--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A struct used to store render target data for the map and inventory doll.
--- @class tes3worldControllerRenderTarget : tes3worldControllerRenderCamera
